// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVwq06tujs-7AfCz6UWPGf_fp9zCd1S64',
    appId: '1:570916285831:web:91e3c329f315515af03722',
    messagingSenderId: '570916285831',
    projectId: 'gamecritic-599ee',
    authDomain: 'gamecritic-599ee.firebaseapp.com',
    storageBucket: 'gamecritic-599ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWvtuvkucTWIPM6Ra1gLVqNsu6OrqtqU',
    appId: '1:570916285831:android:ff73750f5175adb9f03722',
    messagingSenderId: '570916285831',
    projectId: 'gamecritic-599ee',
    storageBucket: 'gamecritic-599ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0aFK3BeQdCvIH-pxitrMctkEr9fsmLk',
    appId: '1:570916285831:ios:dea5220f1d922b2af03722',
    messagingSenderId: '570916285831',
    projectId: 'gamecritic-599ee',
    storageBucket: 'gamecritic-599ee.appspot.com',
    iosClientId: '570916285831-h7v6nbcojku7de3ku5n93vtvli9t03rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamecritic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs0aFK3BeQdCvIH-pxitrMctkEr9fsmLk',
    appId: '1:570916285831:ios:dea5220f1d922b2af03722',
    messagingSenderId: '570916285831',
    projectId: 'gamecritic-599ee',
    storageBucket: 'gamecritic-599ee.appspot.com',
    iosClientId: '570916285831-h7v6nbcojku7de3ku5n93vtvli9t03rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamecritic',
  );
}
